package model.ro;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 15 18:33:28 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppraisalHistHdr_V_ROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    int counter=0;
    
    public AppraisalHistHdr_V_ROVOImpl() {
    }

    /**
     * Returns the variable value for BEmpNumber.
     * @return variable value for BEmpNumber
     */
    public BigDecimal getBEmpNumber() {
        return (BigDecimal) ensureVariableManager().getVariableValue("BEmpNumber");
    }

    /**
     * Sets <code>value</code> for variable BEmpNumber.
     * @param value value to bind as BEmpNumber
     */
    public void setBEmpNumber(BigDecimal value) {
        ensureVariableManager().setVariableValue("BEmpNumber", value);
    }

    /**
     * Returns the variable value for BPlanName.
     * @return variable value for BPlanName
     */
    public String getBPlanName() {
        return (String) ensureVariableManager().getVariableValue("BPlanName");
    }

    /**
     * Sets <code>value</code> for variable BPlanName.
     * @param value value to bind as BPlanName
     */
    public void setBPlanName(String value) {
        ensureVariableManager().setVariableValue("BPlanName", value);
    }
    
    protected void executeQueryForCollection(Object object, Object[] object2,
                                                int i) {
    if (counter > 0) {
               super.executeQueryForCollection(object, object2, i);
           } else {
               counter ++;

           }
    }
}


