package model.ro;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 15 18:33:24 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppraisalHistHdr_V_ROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AppraisalComments,
        AppraisalDate,
        AppraisalFeedback,
        AppraisalHistHdrId,
        AppraisalPeriodEndDate,
        AppraisalPeriodStartDate,
        AppraisalPurpose,
        BusinessGroupName,
        Initiator,
        OverallRating,
        PersonId,
        SuggestedFinalRating,
        EmployeeNumber,
        PlanName,
        AppraiseeName,
        EmployeeType,
        HistoricalType,
        MainAppraiserId,
        DisplayName,
        PersonNumber,
        BusinessUnitName,
        EmailAddress,
        ApprisalHisLine_VO1,
        Oando_AM_Employee_Number_ROVO1_1,
        Oando_AM_Plan_NameRovo1_1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int APPRAISALCOMMENTS = AttributesEnum.AppraisalComments.index();
    public static final int APPRAISALDATE = AttributesEnum.AppraisalDate.index();
    public static final int APPRAISALFEEDBACK = AttributesEnum.AppraisalFeedback.index();
    public static final int APPRAISALHISTHDRID = AttributesEnum.AppraisalHistHdrId.index();
    public static final int APPRAISALPERIODENDDATE = AttributesEnum.AppraisalPeriodEndDate.index();
    public static final int APPRAISALPERIODSTARTDATE = AttributesEnum.AppraisalPeriodStartDate.index();
    public static final int APPRAISALPURPOSE = AttributesEnum.AppraisalPurpose.index();
    public static final int BUSINESSGROUPNAME = AttributesEnum.BusinessGroupName.index();
    public static final int INITIATOR = AttributesEnum.Initiator.index();
    public static final int OVERALLRATING = AttributesEnum.OverallRating.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int SUGGESTEDFINALRATING = AttributesEnum.SuggestedFinalRating.index();
    public static final int EMPLOYEENUMBER = AttributesEnum.EmployeeNumber.index();
    public static final int PLANNAME = AttributesEnum.PlanName.index();
    public static final int APPRAISEENAME = AttributesEnum.AppraiseeName.index();
    public static final int EMPLOYEETYPE = AttributesEnum.EmployeeType.index();
    public static final int HISTORICALTYPE = AttributesEnum.HistoricalType.index();
    public static final int MAINAPPRAISERID = AttributesEnum.MainAppraiserId.index();
    public static final int DISPLAYNAME = AttributesEnum.DisplayName.index();
    public static final int PERSONNUMBER = AttributesEnum.PersonNumber.index();
    public static final int BUSINESSUNITNAME = AttributesEnum.BusinessUnitName.index();
    public static final int EMAILADDRESS = AttributesEnum.EmailAddress.index();
    public static final int APPRISALHISLINE_VO1 = AttributesEnum.ApprisalHisLine_VO1.index();
    public static final int OANDO_AM_EMPLOYEE_NUMBER_ROVO1_1 = AttributesEnum.Oando_AM_Employee_Number_ROVO1_1.index();
    public static final int OANDO_AM_PLAN_NAMEROVO1_1 = AttributesEnum.Oando_AM_Plan_NameRovo1_1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AppraisalHistHdr_V_ROVORowImpl() {
    }
}

