package model.ro;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 20 15:41:24 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Lookup_View_ROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        LookupTypeId,
        LookupTypeCode,
        LookupTypeName,
        LookupTypeNameDispTl,
        LookupValueId,
        LookupValueCode,
        LookupValueNameDisp,
        LookupValueNameDispTl;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int LOOKUPTYPEID = AttributesEnum.LookupTypeId.index();
    public static final int LOOKUPTYPECODE = AttributesEnum.LookupTypeCode.index();
    public static final int LOOKUPTYPENAME = AttributesEnum.LookupTypeName.index();
    public static final int LOOKUPTYPENAMEDISPTL = AttributesEnum.LookupTypeNameDispTl.index();
    public static final int LOOKUPVALUEID = AttributesEnum.LookupValueId.index();
    public static final int LOOKUPVALUECODE = AttributesEnum.LookupValueCode.index();
    public static final int LOOKUPVALUENAMEDISP = AttributesEnum.LookupValueNameDisp.index();
    public static final int LOOKUPVALUENAMEDISPTL = AttributesEnum.LookupValueNameDispTl.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Lookup_View_ROVORowImpl() {
    }
}

