package model.ro;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 14 11:56:58 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Plan_NameRovoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Plan_NameRovoImpl() {
    }
}

