package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 11 19:38:04 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApprisalHisLine_VORowImpl extends ViewRowImpl {


    public static final int ENTITY_APPRISALHISLINE_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AchievementDate,
        ActualValue,
        AppraisalHistHdrId,
        AppraisalHistLineId,
        Comments,
        CompletePercent,
        CreatedBy,
        Detail,
        MeasureComments,
        MeasureName,
        MeasureType,
        MeasureUom,
        MeasurementStyle,
        NextReviewDate,
        ObjectiveComments,
        ObjectiveName,
        ObjectiveStartDate,
        ObjectiveTargetDate,
        SuccessCriteria,
        TargetValue,
        WeightingPercent,
        BusinessGroupName,
        ChargeTo,
        Department,
        EmployeeName,
        EmployeeNumber,
        Entity1,
        HistoricalType,
        OriginalDateOfHire,
        OwningPersonId,
        PersonId,
        PersonTypeDesc,
        Position,
        ScorecardEndDate,
        ScorecardStartDate,
        ScorecardName,
        Status,
        SupervisorName;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACHIEVEMENTDATE = AttributesEnum.AchievementDate.index();
    public static final int ACTUALVALUE = AttributesEnum.ActualValue.index();
    public static final int APPRAISALHISTHDRID = AttributesEnum.AppraisalHistHdrId.index();
    public static final int APPRAISALHISTLINEID = AttributesEnum.AppraisalHistLineId.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int COMPLETEPERCENT = AttributesEnum.CompletePercent.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int DETAIL = AttributesEnum.Detail.index();
    public static final int MEASURECOMMENTS = AttributesEnum.MeasureComments.index();
    public static final int MEASURENAME = AttributesEnum.MeasureName.index();
    public static final int MEASURETYPE = AttributesEnum.MeasureType.index();
    public static final int MEASUREUOM = AttributesEnum.MeasureUom.index();
    public static final int MEASUREMENTSTYLE = AttributesEnum.MeasurementStyle.index();
    public static final int NEXTREVIEWDATE = AttributesEnum.NextReviewDate.index();
    public static final int OBJECTIVECOMMENTS = AttributesEnum.ObjectiveComments.index();
    public static final int OBJECTIVENAME = AttributesEnum.ObjectiveName.index();
    public static final int OBJECTIVESTARTDATE = AttributesEnum.ObjectiveStartDate.index();
    public static final int OBJECTIVETARGETDATE = AttributesEnum.ObjectiveTargetDate.index();
    public static final int SUCCESSCRITERIA = AttributesEnum.SuccessCriteria.index();
    public static final int TARGETVALUE = AttributesEnum.TargetValue.index();
    public static final int WEIGHTINGPERCENT = AttributesEnum.WeightingPercent.index();
    public static final int BUSINESSGROUPNAME = AttributesEnum.BusinessGroupName.index();
    public static final int CHARGETO = AttributesEnum.ChargeTo.index();
    public static final int DEPARTMENT = AttributesEnum.Department.index();
    public static final int EMPLOYEENAME = AttributesEnum.EmployeeName.index();
    public static final int EMPLOYEENUMBER = AttributesEnum.EmployeeNumber.index();
    public static final int ENTITY1 = AttributesEnum.Entity1.index();
    public static final int HISTORICALTYPE = AttributesEnum.HistoricalType.index();
    public static final int ORIGINALDATEOFHIRE = AttributesEnum.OriginalDateOfHire.index();
    public static final int OWNINGPERSONID = AttributesEnum.OwningPersonId.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int PERSONTYPEDESC = AttributesEnum.PersonTypeDesc.index();
    public static final int POSITION = AttributesEnum.Position.index();
    public static final int SCORECARDENDDATE = AttributesEnum.ScorecardEndDate.index();
    public static final int SCORECARDSTARTDATE = AttributesEnum.ScorecardStartDate.index();
    public static final int SCORECARDNAME = AttributesEnum.ScorecardName.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int SUPERVISORNAME = AttributesEnum.SupervisorName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ApprisalHisLine_VORowImpl() {
    }

    /**
     * Gets ApprisalHisLine_EO entity object.
     * @return the ApprisalHisLine_EO
     */
    public EntityImpl getApprisalHisLine_EO() {
        return (EntityImpl) getEntity(ENTITY_APPRISALHISLINE_EO);
    }

    /**
     * Gets the attribute value for ACHIEVEMENT_DATE using the alias name AchievementDate.
     * @return the ACHIEVEMENT_DATE
     */
    public Timestamp getAchievementDate() {
        return (Timestamp) getAttributeInternal(ACHIEVEMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACHIEVEMENT_DATE using the alias name AchievementDate.
     * @param value value to set the ACHIEVEMENT_DATE
     */
    public void setAchievementDate(Timestamp value) {
        setAttributeInternal(ACHIEVEMENTDATE, value);
    }

    /**
     * Gets the attribute value for ACTUAL_VALUE using the alias name ActualValue.
     * @return the ACTUAL_VALUE
     */
    public BigDecimal getActualValue() {
        return (BigDecimal) getAttributeInternal(ACTUALVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTUAL_VALUE using the alias name ActualValue.
     * @param value value to set the ACTUAL_VALUE
     */
    public void setActualValue(BigDecimal value) {
        setAttributeInternal(ACTUALVALUE, value);
    }

    /**
     * Gets the attribute value for APPRAISAL_HIST_HDR_ID using the alias name AppraisalHistHdrId.
     * @return the APPRAISAL_HIST_HDR_ID
     */
    public BigDecimal getAppraisalHistHdrId() {
        return (BigDecimal) getAttributeInternal(APPRAISALHISTHDRID);
    }

    /**
     * Sets <code>value</code> as attribute value for APPRAISAL_HIST_HDR_ID using the alias name AppraisalHistHdrId.
     * @param value value to set the APPRAISAL_HIST_HDR_ID
     */
    public void setAppraisalHistHdrId(BigDecimal value) {
        setAttributeInternal(APPRAISALHISTHDRID, value);
    }

    /**
     * Gets the attribute value for APPRAISAL_HIST_LINE_ID using the alias name AppraisalHistLineId.
     * @return the APPRAISAL_HIST_LINE_ID
     */
    public BigDecimal getAppraisalHistLineId() {
        return (BigDecimal) getAttributeInternal(APPRAISALHISTLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for APPRAISAL_HIST_LINE_ID using the alias name AppraisalHistLineId.
     * @param value value to set the APPRAISAL_HIST_LINE_ID
     */
    public void setAppraisalHistLineId(BigDecimal value) {
        setAttributeInternal(APPRAISALHISTLINEID, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for COMPLETE_PERCENT using the alias name CompletePercent.
     * @return the COMPLETE_PERCENT
     */
    public BigDecimal getCompletePercent() {
        return (BigDecimal) getAttributeInternal(COMPLETEPERCENT);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPLETE_PERCENT using the alias name CompletePercent.
     * @param value value to set the COMPLETE_PERCENT
     */
    public void setCompletePercent(BigDecimal value) {
        setAttributeInternal(COMPLETEPERCENT, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for DETAIL using the alias name Detail.
     * @return the DETAIL
     */
    public String getDetail() {
        return (String) getAttributeInternal(DETAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for DETAIL using the alias name Detail.
     * @param value value to set the DETAIL
     */
    public void setDetail(String value) {
        setAttributeInternal(DETAIL, value);
    }

    /**
     * Gets the attribute value for MEASURE_COMMENTS using the alias name MeasureComments.
     * @return the MEASURE_COMMENTS
     */
    public String getMeasureComments() {
        return (String) getAttributeInternal(MEASURECOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for MEASURE_COMMENTS using the alias name MeasureComments.
     * @param value value to set the MEASURE_COMMENTS
     */
    public void setMeasureComments(String value) {
        setAttributeInternal(MEASURECOMMENTS, value);
    }

    /**
     * Gets the attribute value for MEASURE_NAME using the alias name MeasureName.
     * @return the MEASURE_NAME
     */
    public String getMeasureName() {
        return (String) getAttributeInternal(MEASURENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for MEASURE_NAME using the alias name MeasureName.
     * @param value value to set the MEASURE_NAME
     */
    public void setMeasureName(String value) {
        setAttributeInternal(MEASURENAME, value);
    }

    /**
     * Gets the attribute value for MEASURE_TYPE using the alias name MeasureType.
     * @return the MEASURE_TYPE
     */
    public String getMeasureType() {
        return (String) getAttributeInternal(MEASURETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for MEASURE_TYPE using the alias name MeasureType.
     * @param value value to set the MEASURE_TYPE
     */
    public void setMeasureType(String value) {
        setAttributeInternal(MEASURETYPE, value);
    }

    /**
     * Gets the attribute value for MEASURE_UOM using the alias name MeasureUom.
     * @return the MEASURE_UOM
     */
    public String getMeasureUom() {
        return (String) getAttributeInternal(MEASUREUOM);
    }

    /**
     * Sets <code>value</code> as attribute value for MEASURE_UOM using the alias name MeasureUom.
     * @param value value to set the MEASURE_UOM
     */
    public void setMeasureUom(String value) {
        setAttributeInternal(MEASUREUOM, value);
    }

    /**
     * Gets the attribute value for MEASUREMENT_STYLE using the alias name MeasurementStyle.
     * @return the MEASUREMENT_STYLE
     */
    public String getMeasurementStyle() {
        return (String) getAttributeInternal(MEASUREMENTSTYLE);
    }

    /**
     * Sets <code>value</code> as attribute value for MEASUREMENT_STYLE using the alias name MeasurementStyle.
     * @param value value to set the MEASUREMENT_STYLE
     */
    public void setMeasurementStyle(String value) {
        setAttributeInternal(MEASUREMENTSTYLE, value);
    }

    /**
     * Gets the attribute value for NEXT_REVIEW_DATE using the alias name NextReviewDate.
     * @return the NEXT_REVIEW_DATE
     */
    public Timestamp getNextReviewDate() {
        return (Timestamp) getAttributeInternal(NEXTREVIEWDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for NEXT_REVIEW_DATE using the alias name NextReviewDate.
     * @param value value to set the NEXT_REVIEW_DATE
     */
    public void setNextReviewDate(Timestamp value) {
        setAttributeInternal(NEXTREVIEWDATE, value);
    }

    /**
     * Gets the attribute value for OBJECTIVE_COMMENTS using the alias name ObjectiveComments.
     * @return the OBJECTIVE_COMMENTS
     */
    public String getObjectiveComments() {
        return (String) getAttributeInternal(OBJECTIVECOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECTIVE_COMMENTS using the alias name ObjectiveComments.
     * @param value value to set the OBJECTIVE_COMMENTS
     */
    public void setObjectiveComments(String value) {
        setAttributeInternal(OBJECTIVECOMMENTS, value);
    }

    /**
     * Gets the attribute value for OBJECTIVE_NAME using the alias name ObjectiveName.
     * @return the OBJECTIVE_NAME
     */
    public String getObjectiveName() {
        return (String) getAttributeInternal(OBJECTIVENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECTIVE_NAME using the alias name ObjectiveName.
     * @param value value to set the OBJECTIVE_NAME
     */
    public void setObjectiveName(String value) {
        setAttributeInternal(OBJECTIVENAME, value);
    }

    /**
     * Gets the attribute value for OBJECTIVE_START_DATE using the alias name ObjectiveStartDate.
     * @return the OBJECTIVE_START_DATE
     */
    public Timestamp getObjectiveStartDate() {
        return (Timestamp) getAttributeInternal(OBJECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECTIVE_START_DATE using the alias name ObjectiveStartDate.
     * @param value value to set the OBJECTIVE_START_DATE
     */
    public void setObjectiveStartDate(Timestamp value) {
        setAttributeInternal(OBJECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for OBJECTIVE_TARGET_DATE using the alias name ObjectiveTargetDate.
     * @return the OBJECTIVE_TARGET_DATE
     */
    public Timestamp getObjectiveTargetDate() {
        return (Timestamp) getAttributeInternal(OBJECTIVETARGETDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECTIVE_TARGET_DATE using the alias name ObjectiveTargetDate.
     * @param value value to set the OBJECTIVE_TARGET_DATE
     */
    public void setObjectiveTargetDate(Timestamp value) {
        setAttributeInternal(OBJECTIVETARGETDATE, value);
    }

    /**
     * Gets the attribute value for SUCCESS_CRITERIA using the alias name SuccessCriteria.
     * @return the SUCCESS_CRITERIA
     */
    public String getSuccessCriteria() {
        return (String) getAttributeInternal(SUCCESSCRITERIA);
    }

    /**
     * Sets <code>value</code> as attribute value for SUCCESS_CRITERIA using the alias name SuccessCriteria.
     * @param value value to set the SUCCESS_CRITERIA
     */
    public void setSuccessCriteria(String value) {
        setAttributeInternal(SUCCESSCRITERIA, value);
    }

    /**
     * Gets the attribute value for TARGET_VALUE using the alias name TargetValue.
     * @return the TARGET_VALUE
     */
    public BigDecimal getTargetValue() {
        return (BigDecimal) getAttributeInternal(TARGETVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for TARGET_VALUE using the alias name TargetValue.
     * @param value value to set the TARGET_VALUE
     */
    public void setTargetValue(BigDecimal value) {
        setAttributeInternal(TARGETVALUE, value);
    }

    /**
     * Gets the attribute value for WEIGHTING_PERCENT using the alias name WeightingPercent.
     * @return the WEIGHTING_PERCENT
     */
    public BigDecimal getWeightingPercent() {
        return (BigDecimal) getAttributeInternal(WEIGHTINGPERCENT);
    }

    /**
     * Sets <code>value</code> as attribute value for WEIGHTING_PERCENT using the alias name WeightingPercent.
     * @param value value to set the WEIGHTING_PERCENT
     */
    public void setWeightingPercent(BigDecimal value) {
        setAttributeInternal(WEIGHTINGPERCENT, value);
    }

    /**
     * Gets the attribute value for BUSINESS_GROUP_NAME using the alias name BusinessGroupName.
     * @return the BUSINESS_GROUP_NAME
     */
    public String getBusinessGroupName() {
        return (String) getAttributeInternal(BUSINESSGROUPNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_GROUP_NAME using the alias name BusinessGroupName.
     * @param value value to set the BUSINESS_GROUP_NAME
     */
    public void setBusinessGroupName(String value) {
        setAttributeInternal(BUSINESSGROUPNAME, value);
    }

    /**
     * Gets the attribute value for CHARGE_TO using the alias name ChargeTo.
     * @return the CHARGE_TO
     */
    public String getChargeTo() {
        return (String) getAttributeInternal(CHARGETO);
    }

    /**
     * Sets <code>value</code> as attribute value for CHARGE_TO using the alias name ChargeTo.
     * @param value value to set the CHARGE_TO
     */
    public void setChargeTo(String value) {
        setAttributeInternal(CHARGETO, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT using the alias name Department.
     * @return the DEPARTMENT
     */
    public String getDepartment() {
        return (String) getAttributeInternal(DEPARTMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT using the alias name Department.
     * @param value value to set the DEPARTMENT
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_NAME using the alias name EmployeeName.
     * @return the EMPLOYEE_NAME
     */
    public String getEmployeeName() {
        return (String) getAttributeInternal(EMPLOYEENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_NAME using the alias name EmployeeName.
     * @param value value to set the EMPLOYEE_NAME
     */
    public void setEmployeeName(String value) {
        setAttributeInternal(EMPLOYEENAME, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_NUMBER using the alias name EmployeeNumber.
     * @return the EMPLOYEE_NUMBER
     */
    public BigDecimal getEmployeeNumber() {
        return (BigDecimal) getAttributeInternal(EMPLOYEENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_NUMBER using the alias name EmployeeNumber.
     * @param value value to set the EMPLOYEE_NUMBER
     */
    public void setEmployeeNumber(BigDecimal value) {
        setAttributeInternal(EMPLOYEENUMBER, value);
    }

    /**
     * Gets the attribute value for ENTITY using the alias name Entity1.
     * @return the ENTITY
     */
    public String getEntity1() {
        return (String) getAttributeInternal(ENTITY1);
    }

    /**
     * Sets <code>value</code> as attribute value for ENTITY using the alias name Entity1.
     * @param value value to set the ENTITY
     */
    public void setEntity1(String value) {
        setAttributeInternal(ENTITY1, value);
    }

    /**
     * Gets the attribute value for HISTORICAL_TYPE using the alias name HistoricalType.
     * @return the HISTORICAL_TYPE
     */
    public String getHistoricalType() {
        return (String) getAttributeInternal(HISTORICALTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for HISTORICAL_TYPE using the alias name HistoricalType.
     * @param value value to set the HISTORICAL_TYPE
     */
    public void setHistoricalType(String value) {
        setAttributeInternal(HISTORICALTYPE, value);
    }

    /**
     * Gets the attribute value for ORIGINAL_DATE_OF_HIRE using the alias name OriginalDateOfHire.
     * @return the ORIGINAL_DATE_OF_HIRE
     */
    public Timestamp getOriginalDateOfHire() {
        return (Timestamp) getAttributeInternal(ORIGINALDATEOFHIRE);
    }

    /**
     * Sets <code>value</code> as attribute value for ORIGINAL_DATE_OF_HIRE using the alias name OriginalDateOfHire.
     * @param value value to set the ORIGINAL_DATE_OF_HIRE
     */
    public void setOriginalDateOfHire(Timestamp value) {
        setAttributeInternal(ORIGINALDATEOFHIRE, value);
    }

    /**
     * Gets the attribute value for OWNING_PERSON_ID using the alias name OwningPersonId.
     * @return the OWNING_PERSON_ID
     */
    public BigDecimal getOwningPersonId() {
        return (BigDecimal) getAttributeInternal(OWNINGPERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for OWNING_PERSON_ID using the alias name OwningPersonId.
     * @param value value to set the OWNING_PERSON_ID
     */
    public void setOwningPersonId(BigDecimal value) {
        setAttributeInternal(OWNINGPERSONID, value);
    }

    /**
     * Gets the attribute value for PERSON_ID using the alias name PersonId.
     * @return the PERSON_ID
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId.
     * @param value value to set the PERSON_ID
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for PERSON_TYPE_DESC using the alias name PersonTypeDesc.
     * @return the PERSON_TYPE_DESC
     */
    public String getPersonTypeDesc() {
        return (String) getAttributeInternal(PERSONTYPEDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_TYPE_DESC using the alias name PersonTypeDesc.
     * @param value value to set the PERSON_TYPE_DESC
     */
    public void setPersonTypeDesc(String value) {
        setAttributeInternal(PERSONTYPEDESC, value);
    }

    /**
     * Gets the attribute value for POSITION using the alias name Position.
     * @return the POSITION
     */
    public String getPosition() {
        return (String) getAttributeInternal(POSITION);
    }

    /**
     * Sets <code>value</code> as attribute value for POSITION using the alias name Position.
     * @param value value to set the POSITION
     */
    public void setPosition(String value) {
        setAttributeInternal(POSITION, value);
    }

    /**
     * Gets the attribute value for SCORECARD_END_DATE using the alias name ScorecardEndDate.
     * @return the SCORECARD_END_DATE
     */
    public Timestamp getScorecardEndDate() {
        return (Timestamp) getAttributeInternal(SCORECARDENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SCORECARD_END_DATE using the alias name ScorecardEndDate.
     * @param value value to set the SCORECARD_END_DATE
     */
    public void setScorecardEndDate(Timestamp value) {
        setAttributeInternal(SCORECARDENDDATE, value);
    }

    /**
     * Gets the attribute value for SCORECARD_START_DATE using the alias name ScorecardStartDate.
     * @return the SCORECARD_START_DATE
     */
    public Timestamp getScorecardStartDate() {
        return (Timestamp) getAttributeInternal(SCORECARDSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SCORECARD_START_DATE using the alias name ScorecardStartDate.
     * @param value value to set the SCORECARD_START_DATE
     */
    public void setScorecardStartDate(Timestamp value) {
        setAttributeInternal(SCORECARDSTARTDATE, value);
    }

    /**
     * Gets the attribute value for SCORECARD_NAME using the alias name ScorecardName.
     * @return the SCORECARD_NAME
     */
    public String getScorecardName() {
        return (String) getAttributeInternal(SCORECARDNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for SCORECARD_NAME using the alias name ScorecardName.
     * @param value value to set the SCORECARD_NAME
     */
    public void setScorecardName(String value) {
        setAttributeInternal(SCORECARDNAME, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for SUPERVISOR_NAME using the alias name SupervisorName.
     * @return the SUPERVISOR_NAME
     */
    public String getSupervisorName() {
        return (String) getAttributeInternal(SUPERVISORNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPERVISOR_NAME using the alias name SupervisorName.
     * @param value value to set the SUPERVISOR_NAME
     */
    public void setSupervisorName(String value) {
        setAttributeInternal(SUPERVISORNAME, value);
    }
}

