package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 12 11:25:13 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IntroLtrLines_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public IntroLtrLines_VOImpl() {
    }
}

