package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import model.eo.IntroLtrHdr_EOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.Row;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 09 15:24:55 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IntroLtrHdr_VORowImpl extends ViewRowImpl {


    public static final int ENTITY_INTROLTRHDR_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ApprovedStatus,
        BusinessUnitId,
        CreatedBy,
        CreationDate,
        DestCountryCode,
        IntroLtrHdrId,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        PersonId,
        Remarks,
        TravelPurposeCode,
        TravelRequestNo,
        Trans_EmpName,
        Trans_EmpNo,
        Trans_EmailId,
        Trans_Country,
        Trans_BusinessGroup,
        IntroLtrLines_VO,
        Employee_View_ROVO,
        Lookup_TravelPurpose,
        Employee_View_Ref,
        Country_Ref,
        Business_Group_View_ROVO1,
        Business_Group_Ref,
        Country_ROVO,
        BusinessGrpROVO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int APPROVEDSTATUS = AttributesEnum.ApprovedStatus.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int DESTCOUNTRYCODE = AttributesEnum.DestCountryCode.index();
    public static final int INTROLTRHDRID = AttributesEnum.IntroLtrHdrId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int TRAVELPURPOSECODE = AttributesEnum.TravelPurposeCode.index();
    public static final int TRAVELREQUESTNO = AttributesEnum.TravelRequestNo.index();
    public static final int TRANS_EMPNAME = AttributesEnum.Trans_EmpName.index();
    public static final int TRANS_EMPNO = AttributesEnum.Trans_EmpNo.index();
    public static final int TRANS_EMAILID = AttributesEnum.Trans_EmailId.index();
    public static final int TRANS_COUNTRY = AttributesEnum.Trans_Country.index();
    public static final int TRANS_BUSINESSGROUP = AttributesEnum.Trans_BusinessGroup.index();
    public static final int INTROLTRLINES_VO = AttributesEnum.IntroLtrLines_VO.index();
    public static final int EMPLOYEE_VIEW_ROVO = AttributesEnum.Employee_View_ROVO.index();
    public static final int LOOKUP_TRAVELPURPOSE = AttributesEnum.Lookup_TravelPurpose.index();
    public static final int EMPLOYEE_VIEW_REF = AttributesEnum.Employee_View_Ref.index();
    public static final int COUNTRY_REF = AttributesEnum.Country_Ref.index();
    public static final int BUSINESS_GROUP_VIEW_ROVO1 = AttributesEnum.Business_Group_View_ROVO1.index();
    public static final int BUSINESS_GROUP_REF = AttributesEnum.Business_Group_Ref.index();
    public static final int COUNTRY_ROVO = AttributesEnum.Country_ROVO.index();
    public static final int BUSINESSGRPROVO = AttributesEnum.BusinessGrpROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public IntroLtrHdr_VORowImpl() {
    }

    /**
     * Gets IntroLtrHdr_EO entity object.
     * @return the IntroLtrHdr_EO
     */
    public IntroLtrHdr_EOImpl getIntroLtrHdr_EO() {
        return (IntroLtrHdr_EOImpl) getEntity(ENTITY_INTROLTRHDR_EO);
    }

    /**
     * Gets the attribute value for APPROVED_STATUS using the alias name ApprovedStatus.
     * @return the APPROVED_STATUS
     */
    public String getApprovedStatus() {
        return (String) getAttributeInternal(APPROVEDSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVED_STATUS using the alias name ApprovedStatus.
     * @param value value to set the APPROVED_STATUS
     */
    public void setApprovedStatus(String value) {
        setAttributeInternal(APPROVEDSTATUS, value);
    }

    /**
     * Gets the attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @return the BUSINESS_UNIT_ID
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @param value value to set the BUSINESS_UNIT_ID
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for DEST_COUNTRY_CODE using the alias name DestCountryCode.
     * @return the DEST_COUNTRY_CODE
     */
    public String getDestCountryCode() {
        return (String) getAttributeInternal(DESTCOUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for DEST_COUNTRY_CODE using the alias name DestCountryCode.
     * @param value value to set the DEST_COUNTRY_CODE
     */
    public void setDestCountryCode(String value) {
        setAttributeInternal(DESTCOUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for INTRO_LTR_HDR_ID using the alias name IntroLtrHdrId.
     * @return the INTRO_LTR_HDR_ID
     */
    public BigDecimal getIntroLtrHdrId() {
        return (BigDecimal) getAttributeInternal(INTROLTRHDRID);
    }

    /**
     * Sets <code>value</code> as attribute value for INTRO_LTR_HDR_ID using the alias name IntroLtrHdrId.
     * @param value value to set the INTRO_LTR_HDR_ID
     */
    public void setIntroLtrHdrId(BigDecimal value) {
        setAttributeInternal(INTROLTRHDRID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }


    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for PERSON_ID using the alias name PersonId.
     * @return the PERSON_ID
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId.
     * @param value value to set the PERSON_ID
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for TRAVEL_PURPOSE_CODE using the alias name TravelPurposeCode.
     * @return the TRAVEL_PURPOSE_CODE
     */
    public String getTravelPurposeCode() {
        return (String) getAttributeInternal(TRAVELPURPOSECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRAVEL_PURPOSE_CODE using the alias name TravelPurposeCode.
     * @param value value to set the TRAVEL_PURPOSE_CODE
     */
    public void setTravelPurposeCode(String value) {
        setAttributeInternal(TRAVELPURPOSECODE, value);
    }

    /**
     * Gets the attribute value for TRAVEL_REQUEST_NO using the alias name TravelRequestNo.
     * @return the TRAVEL_REQUEST_NO
     */
    public String getTravelRequestNo() {
        return (String) getAttributeInternal(TRAVELREQUESTNO);
    }


    /**
     * Sets <code>value</code> as attribute value for TRAVEL_REQUEST_NO using the alias name TravelRequestNo.
     * @param value value to set the TRAVEL_REQUEST_NO
     */
    public void setTravelRequestNo(String value) {
        setAttributeInternal(TRAVELREQUESTNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_EmpName.
     * @return the Trans_EmpName
     */
    public String getTrans_EmpName() {
        BigDecimal personId = null;
        String fullName = null;
        if (getPersonId() != null) {
            personId = getPersonId();
            Row[] empRows;
            empRows = getEmployee_View_Ref().getFilteredRows("PersonId", personId);
            if (empRows.length > 0) {
                fullName = empRows[0].getAttribute("FullName").toString();
            }
            return fullName;

        } else {
            return (String) getAttributeInternal(TRANS_EMPNAME);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_EmpName.
     * @param value value to set the  Trans_EmpName
     */
    public void setTrans_EmpName(String value) {
        setAttributeInternal(TRANS_EMPNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_EmpNo.
     * @return the Trans_EmpNo
     */
    public String getTrans_EmpNo() {
        BigDecimal personId = null;
        String empNO = null;
        if (getPersonId() != null) {
            personId = getPersonId();
            Row[] empRows;
            empRows = getEmployee_View_Ref().getFilteredRows("PersonId", personId);
            if (empRows.length > 0) {
                empNO = empRows[0].getAttribute("PersonNumber").toString();
            }
            return empNO;

        } else {
            return (String) getAttributeInternal(TRANS_EMPNO);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_EmpNo.
     * @param value value to set the  Trans_EmpNo
     */
    public void setTrans_EmpNo(String value) {
        setAttributeInternal(TRANS_EMPNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_EmailId.
     * @return the Trans_EmailId
     */
    public String getTrans_EmailId() {
        BigDecimal personId = null;
        String email = null;
        if (getPersonId() != null) {
            personId = getPersonId();
            Row[] empRows;
            empRows = getEmployee_View_Ref().getFilteredRows("PersonId", personId);
            if (empRows.length > 0) {
                email = empRows[0].getAttribute("EmailAddress").toString();
            }
            return email;

        } else {
            return (String) getAttributeInternal(TRANS_EMAILID);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_EmailId.
     * @param value value to set the  Trans_EmailId
     */
    public void setTrans_EmailId(String value) {
        setAttributeInternal(TRANS_EMAILID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Country.
     * @return the Trans_Country
     */
    public String getTrans_Country() {
        String countryCode = null;
        String countryName = null;
        if (getDestCountryCode() != null) {
            countryCode = getDestCountryCode();
            Row[] countryRows;
            countryRows = getCountry_Ref().getFilteredRows("TerritoryCode", countryCode);
            if (countryRows.length > 0) {
                countryName = countryRows[0].getAttribute("TerritoryShortName").toString();
            }
            return countryName;

        } else {
            return (String) getAttributeInternal(TRANS_COUNTRY);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calcul ated attribute Trans_Country.
     * @param value value to set the  Trans_Country
     */
    public void setTrans_Country(String value) {
        setAttributeInternal(TRANS_COUNTRY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_BusinessGroup.
     * @return the Trans_BusinessGroup
     */
    public String getTrans_BusinessGroup() {
        BigDecimal OrgId = null;
        String orgName = null;
        if (getBusinessUnitId() != null) {
            OrgId = getBusinessUnitId();
            Row[] orgRows;
            orgRows = getBusiness_Group_Ref().getFilteredRows("OrganizationId", OrgId);
            if (orgRows.length > 0) {
                orgName = orgRows[0].getAttribute("Name").toString();
            }
            return orgName;

        } else {
            return (String) getAttributeInternal(TRANS_BUSINESSGROUP);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_BusinessGroup.
     * @param value value to set the  Trans_BusinessGroup
     */
    public void setTrans_BusinessGroup(String value) {
        setAttributeInternal(TRANS_BUSINESSGROUP, value);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link IntroLtrLines_VO.
     */
    public RowIterator getIntroLtrLines_VO() {
        return (RowIterator) getAttributeInternal(INTROLTRLINES_VO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Employee_View_ROVO.
     */
    public RowSet getEmployee_View_ROVO() {
        return (RowSet) getAttributeInternal(EMPLOYEE_VIEW_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_TravelPurpose.
     */
    public RowSet getLookup_TravelPurpose() {
        return (RowSet) getAttributeInternal(LOOKUP_TRAVELPURPOSE);
    }


    /**
     * Gets the view accessor <code>RowSet</code> Employee_View_Ref.
     */
    public RowSet getEmployee_View_Ref() {
        return (RowSet) getAttributeInternal(EMPLOYEE_VIEW_REF);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Country_Ref.
     */
    public RowSet getCountry_Ref() {
        return (RowSet) getAttributeInternal(COUNTRY_REF);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Business_Group_View_ROVO1.
     */
    public RowSet getBusiness_Group_View_ROVO1() {
        return (RowSet) getAttributeInternal(BUSINESS_GROUP_VIEW_ROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Business_Group_Ref.
     */
    public RowSet getBusiness_Group_Ref() {
        return (RowSet) getAttributeInternal(BUSINESS_GROUP_REF);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Country_ROVO.
     */
    public RowSet getCountry_ROVO() {
        return (RowSet) getAttributeInternal(COUNTRY_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BusinessGrpROVO.
     */
    public RowSet getBusinessGrpROVO() {
        return (RowSet) getAttributeInternal(BUSINESSGRPROVO);
    }

}

