package model.am;

import java.math.BigDecimal;


import model.am.common.Oando_AM;

import model.ro.AppraisalHistHdr_V_ROVOImpl;
import model.ro.Lookup_View_ROVOImpl;


import model.ro.Plan_NameRovoImpl;

import model.vo.ApprisalHisHdr_VOImpl;


import model.vo.ApprisalHisLine_VOImpl;
import model.vo.IntroLtrHdr_VOImpl;
import model.vo.IntroLtrLines_VOImpl;

import oracle.adf.share.ADFContext;

import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 22 10:07:33 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Oando_AMImpl extends ApplicationModuleImpl implements Oando_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public Oando_AMImpl() {
    }

    /**
     * Container's getter for Business_Group_View_ROVO.
     * @return Business_Group_View_ROVO
     */
    public ViewObjectImpl getBusiness_Group_View_ROVO() {
        return (ViewObjectImpl) findViewObject("Business_Group_View_ROVO");
    }

    /**
     * Container's getter for Employee_Depnd_View_ROVO.
     * @return Employee_Depnd_View_ROVO
     */
    public ViewObjectImpl getEmployee_Depnd_View_ROVO() {
        return (ViewObjectImpl) findViewObject("Employee_Depnd_View_ROVO");
    }

    /**
     * Container's getter for Employee_View_ROVO.
     * @return Employee_View_ROVO
     */
    public ViewObjectImpl getEmployee_View_ROVO() {
        return (ViewObjectImpl) findViewObject("Employee_View_ROVO");
    }

    /**
     * Container's getter for Lookup_View_ROVO.
     * @return Lookup_View_ROVO
     */
    public Lookup_View_ROVOImpl getLookup_View_ROVO() {
        return (Lookup_View_ROVOImpl) findViewObject("Lookup_View_ROVO");
    }

    /**
     * Container's getter for IntroLtrHdr_VO.
     * @return IntroLtrHdr_VO
     */
    public IntroLtrHdr_VOImpl getIntroLtrHdr_VO() {
        return (IntroLtrHdr_VOImpl) findViewObject("IntroLtrHdr_VO");
    }

    /**
     * Container's getter for IntroLtrLines_VO.
     * @return IntroLtrLines_VO
     */
    public IntroLtrLines_VOImpl getIntroLtrLines_VO() {
        return (IntroLtrLines_VOImpl) findViewObject("IntroLtrLines_VO");
    }

    /**
     * Container's getter for Country_ROVO1.
     * @return Country_ROVO1
     */
    public ViewObjectImpl getCountry_ROVO1() {
        return (ViewObjectImpl) findViewObject("Country_ROVO1");
    }

    /**
     * Container's getter for RelationShip_ROVO.
     * @return RelationShip_ROVO
     */
    public ViewObjectImpl getRelationShip_ROVO() {
        return (ViewObjectImpl) findViewObject("RelationShip_ROVO");
    }

    /**
     * Container's getter for Xxgl_Ledgers1.
     * @return Xxgl_Ledgers1
     */
    public ViewObjectImpl getXxgl_Ledgers1() {
        return (ViewObjectImpl) findViewObject("Xxgl_Ledgers1");
    }

    /**
     * Container's getter for Xxhr_BusinessUnit_view_ROVO1.
     * @return Xxhr_BusinessUnit_view_ROVO1
     */
    public ViewObjectImpl getXxhr_BusinessUnit_view_ROVO1() {
        return (ViewObjectImpl) findViewObject("Xxhr_BusinessUnit_view_ROVO1");
    }
   
    /**
     * Container's getter for Code_Combination_ROVO1.
     * @return Code_Combination_ROVO1
     */
    public ViewObjectImpl getCode_Combination_ROVO1() {
        return (ViewObjectImpl) findViewObject("Code_Combination_ROVO1");
    }

    /**
     * Container's getter for Users_ROVO.
     * @return Users_ROVO
     */
    public ViewObjectImpl getUsers_ROVO() {
        return (ViewObjectImpl) findViewObject("Users_ROVO");
    }

    /**
     * Container's getter for IntroHdrLine_VL1.
     * @return IntroHdrLine_VL1
     */
    public ViewLinkImpl getIntroHdrLine_VL1() {
        return (ViewLinkImpl) findViewLink("IntroHdrLine_VL1");
    }  

    public BigDecimal getPersonId(String userName) {

        BigDecimal personId = new BigDecimal(0);
        String  PersonNumber ="";
        String BusinessGroup = "";
        String EmailAddress = "";
        String FullName = "";
        ViewObjectImpl vo = this.getUsers_ROVO();
        ViewCriteria vc = vo.createViewCriteria();
        ViewCriteriaRow vcRow = vc.createViewCriteriaRow();
        vcRow.setAttribute("Username", userName);
        vc.addRow(vcRow);
        vo.applyViewCriteria(vc);
        vo.executeQuery();
        if (vo.getEstimatedRowCount() > 0) {
            personId = (BigDecimal) vo.first().getAttribute("PersonId");
            ADFContext.getCurrent()
                      .getSessionScope()
                      .put("personId", personId);
        }
        ViewObjectImpl vo1 = this.getEmployee_View_ROVO();
        ViewCriteria vc1 = vo1.getViewCriteria("getPersonNumberCriteria");
        vo1.applyViewCriteria(vc1);
        vo1.setNamedWhereClauseParam("p_personNumber", personId);
        vo1.executeQuery();
        if (vo1.getEstimatedRowCount() > 0) {
            PersonNumber = (String) vo1.first().getAttribute("PersonNumber");
            FullName = (String) vo1.first().getAttribute("DisplayName");
            EmailAddress = (String) vo1.first().getAttribute("EmailAddress");
            BusinessGroup = (String) vo1.first().getAttribute("BusinessUnitName");
            ADFContext.getCurrent()
                      .getSessionScope()
                      .put("PersonNumber", PersonNumber);
            ADFContext.getCurrent()
                      .getSessionScope()
                      .put("DisplayName", FullName);
            ADFContext.getCurrent()
                      .getSessionScope()
                      .put("EmailAddress", EmailAddress);
            ADFContext.getCurrent()
                      .getSessionScope()
                      .put("BusinessUnitName", BusinessGroup);
            System.out.println("PersonId---- " + personId);
        }
        

        return personId;
    }

    public void filterUser() {
        String personNumber = ADFContext.getCurrent()
                                    .getSessionScope()
                                    .get("PersonNumber")
                                    .toString();
        System.err.println(personNumber + "--------------User Name");
        ViewObjectImpl vo = getIntroLtrHdr_VO();
       // vo.setNamedWhereClauseParam("b_empnum", personNumber);
        vo.executeQuery();
        System.err.println(vo.getEstimatedRowCount() + "-------Row Count");
    }
    
    public void filter() {
        String personNumber = ADFContext.getCurrent()
                                    .getSessionScope()
                                    .get("PersonNumber")
                                    .toString();
        System.err.println(personNumber + "--------------User Name");
        ViewObjectImpl vo = getAppraisalHistHdr_V_ROVO1();
        vo.setNamedWhereClauseParam("BEmpNumber", personNumber);
        vo.executeQuery();
        System.err.println(vo.getEstimatedRowCount() + "===-------Row Count");
    }

    /**
     * Container's getter for BusinessGrpROVO1.
     * @return BusinessGrpROVO1
     */
    public ViewObjectImpl getBusinessGrpROVO() {
        return (ViewObjectImpl) findViewObject("BusinessGrpROVO");
    }

    /**
     * Container's getter for ApprisalHisHdr_VO1.
     * @return ApprisalHisHdr_VO1
     */
    public ApprisalHisHdr_VOImpl getApprisalHisHdr_VO() {
        return (ApprisalHisHdr_VOImpl) findViewObject("ApprisalHisHdr_VO");
    }

    /**
     * Container's getter for ApprisalHisLine_VO1.
     * @return ApprisalHisLine_VO1
     */
    public ApprisalHisLine_VOImpl getApprisalHisLine_VO() {
        return (ApprisalHisLine_VOImpl) findViewObject("ApprisalHisLine_VO");
    }

    /**
     * Container's getter for ApprisalHistory1.
     * @return ApprisalHistory1
     */
    public ViewLinkImpl getApprisalHistory1() {
        return (ViewLinkImpl) findViewLink("ApprisalHistory1");
    }


    /**
     * Container's getter for PlanNameROVO1.
     * @return PlanNameROVO1
     */
    public ViewObjectImpl getPlanNameROVO() {
        return (ViewObjectImpl) findViewObject("PlanNameROVO");
    }

    /**
     * Container's getter for Employee_Number_ROVO1.
     * @return Employee_Number_ROVO1
     */
    public ViewObjectImpl getEmployee_Number_ROVO1() {
        return (ViewObjectImpl) findViewObject("Employee_Number_ROVO1");
    }

    /**
     * Container's getter for Plan_NameRovo1.
     * @return Plan_NameRovo1
     */
    public Plan_NameRovoImpl getPlan_NameRovo1() {
        return (Plan_NameRovoImpl) findViewObject("Plan_NameRovo1");
    }

    /**
     * Container's getter for AppraisalHistHdr_V_ROVO1.
     * @return AppraisalHistHdr_V_ROVO1
     */
    public AppraisalHistHdr_V_ROVOImpl getAppraisalHistHdr_V_ROVO1() {
        return (AppraisalHistHdr_V_ROVOImpl) findViewObject("AppraisalHistHdr_V_ROVO1");
    }


    /**
     * Container's getter for AppraisalHistHdr_V_ROVO2.
     * @return AppraisalHistHdr_V_ROVO2
     */
    public AppraisalHistHdr_V_ROVOImpl getAppraisalHistHdr_V_ROVO2() {
        return (AppraisalHistHdr_V_ROVOImpl) findViewObject("AppraisalHistHdr_V_ROVO2");
    }

    /**
     * Container's getter for ApprisalHisLine_VO2.
     * @return ApprisalHisLine_VO2
     */
    public ApprisalHisLine_VOImpl getApprisalHisLine_VO2() {
        return (ApprisalHisLine_VOImpl) findViewObject("ApprisalHisLine_VO2");
    }

    /**
     * Container's getter for NumberPlanVL2.
     * @return NumberPlanVL2
     */
    public ViewLinkImpl getNumberPlanVL2() {
        return (ViewLinkImpl) findViewLink("NumberPlanVL2");
    }


    /**
     * Container's getter for ApprisalHisLine_VO3.
     * @return ApprisalHisLine_VO3
     */
    public ApprisalHisLine_VOImpl getApprisalHisLine_VO3() {
        return (ApprisalHisLine_VOImpl) findViewObject("ApprisalHisLine_VO3");
    }

    /**
     * Container's getter for NumberPlanVL1.
     * @return NumberPlanVL1
     */
    public ViewLinkImpl getNumberPlanVL1() {
        return (ViewLinkImpl) findViewLink("NumberPlanVL1");
    }
}

