package model.am.common;

import java.math.BigDecimal;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 22 16:08:45 IST 2019
// ---------------------------------------------------------------------
public interface Oando_AM extends ApplicationModule {
    BigDecimal getPersonId(String userName);
    
    void filterUser();

    void filter();
}

