package model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 08 09:10:52 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IntroLtrHdr_EOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IntroLtrHdrId,
        TravelRequestNo,
        PersonId,
        BusinessUnitId,
        TravelPurposeCode,
        DestCountryCode,
        Remarks,
        ApprovedStatus,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        IntroLtrLines_EO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int INTROLTRHDRID = AttributesEnum.IntroLtrHdrId.index();
    public static final int TRAVELREQUESTNO = AttributesEnum.TravelRequestNo.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int TRAVELPURPOSECODE = AttributesEnum.TravelPurposeCode.index();
    public static final int DESTCOUNTRYCODE = AttributesEnum.DestCountryCode.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int APPROVEDSTATUS = AttributesEnum.ApprovedStatus.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int INTROLTRLINES_EO = AttributesEnum.IntroLtrLines_EO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public IntroLtrHdr_EOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.IntroLtrHdr_EO");
    }


    /**
     * Gets the attribute value for IntroLtrHdrId, using the alias name IntroLtrHdrId.
     * @return the value of IntroLtrHdrId
     */
    public BigDecimal getIntroLtrHdrId() {
        return (BigDecimal) getAttributeInternal(INTROLTRHDRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntroLtrHdrId.
     * @param value value to set the IntroLtrHdrId
     */
    public void setIntroLtrHdrId(BigDecimal value) {
        setAttributeInternal(INTROLTRHDRID, value);
    }

    /**
     * Gets the attribute value for TravelRequestNo, using the alias name TravelRequestNo.
     * @return the value of TravelRequestNo
     */
    public String getTravelRequestNo() {
        return (String) getAttributeInternal(TRAVELREQUESTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for TravelRequestNo.
     * @param value value to set the TravelRequestNo
     */
    public void setTravelRequestNo(String value) {
        setAttributeInternal(TRAVELREQUESTNO, value);
    }

    /**
     * Gets the attribute value for PersonId, using the alias name PersonId.
     * @return the value of PersonId
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PersonId.
     * @param value value to set the PersonId
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for BusinessUnitId, using the alias name BusinessUnitId.
     * @return the value of BusinessUnitId
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BusinessUnitId.
     * @param value value to set the BusinessUnitId
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for TravelPurposeCode, using the alias name TravelPurposeCode.
     * @return the value of TravelPurposeCode
     */
    public String getTravelPurposeCode() {
        return (String) getAttributeInternal(TRAVELPURPOSECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TravelPurposeCode.
     * @param value value to set the TravelPurposeCode
     */
    public void setTravelPurposeCode(String value) {
        setAttributeInternal(TRAVELPURPOSECODE, value);
    }

    /**
     * Gets the attribute value for DestCountryCode, using the alias name DestCountryCode.
     * @return the value of DestCountryCode
     */
    public String getDestCountryCode() {
        return (String) getAttributeInternal(DESTCOUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DestCountryCode.
     * @param value value to set the DestCountryCode
     */
    public void setDestCountryCode(String value) {
        setAttributeInternal(DESTCOUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for ApprovedStatus, using the alias name ApprovedStatus.
     * @return the value of ApprovedStatus
     */
    public String getApprovedStatus() {
        return (String) getAttributeInternal(APPROVEDSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApprovedStatus.
     * @param value value to set the ApprovedStatus
     */
    public void setApprovedStatus(String value) {
        setAttributeInternal(APPROVEDSTATUS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the value of LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getIntroLtrLines_EO() {
        return (RowIterator) getAttributeInternal(INTROLTRLINES_EO);
    }


    /**
     * @param introLtrHdrId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal introLtrHdrId) {
        return new Key(new Object[] { introLtrHdrId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }
}

