package model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 08 09:12:23 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IntroLtrLines_EOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IntroLtrLineId,
        IntroLtrHdrId,
        ReleationTypeCode,
        PersonId,
        PassportNo,
        DateOfBirth,
        PlaceBirth,
        PassportIssueDate,
        PassportEndDate,
        ProTravelDate,
        ExpReturnDate,
        Remarks,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        Activeyn,
        IntroLtrHdr_EO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return IntroLtrLines_EOImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return IntroLtrLines_EOImpl.AttributesEnum.firstIndex() + IntroLtrLines_EOImpl.AttributesEnum
                                                                                          .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = IntroLtrLines_EOImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int INTROLTRLINEID = AttributesEnum.IntroLtrLineId.index();
    public static final int INTROLTRHDRID = AttributesEnum.IntroLtrHdrId.index();
    public static final int RELEATIONTYPECODE = AttributesEnum.ReleationTypeCode.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int PASSPORTNO = AttributesEnum.PassportNo.index();
    public static final int DATEOFBIRTH = AttributesEnum.DateOfBirth.index();
    public static final int PLACEBIRTH = AttributesEnum.PlaceBirth.index();
    public static final int PASSPORTISSUEDATE = AttributesEnum.PassportIssueDate.index();
    public static final int PASSPORTENDDATE = AttributesEnum.PassportEndDate.index();
    public static final int PROTRAVELDATE = AttributesEnum.ProTravelDate.index();
    public static final int EXPRETURNDATE = AttributesEnum.ExpReturnDate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ACTIVEYN = AttributesEnum.Activeyn.index();
    public static final int INTROLTRHDR_EO = AttributesEnum.IntroLtrHdr_EO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public IntroLtrLines_EOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.IntroLtrLines_EO");
    }


    /**
     * Gets the attribute value for IntroLtrLineId, using the alias name IntroLtrLineId.
     * @return the value of IntroLtrLineId
     */
    public BigDecimal getIntroLtrLineId() {
        return (BigDecimal) getAttributeInternal(INTROLTRLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntroLtrLineId.
     * @param value value to set the IntroLtrLineId
     */
    public void setIntroLtrLineId(BigDecimal value) {
        setAttributeInternal(INTROLTRLINEID, value);
    }

    /**
     * Gets the attribute value for IntroLtrHdrId, using the alias name IntroLtrHdrId.
     * @return the value of IntroLtrHdrId
     */
    public BigDecimal getIntroLtrHdrId() {
        return (BigDecimal) getAttributeInternal(INTROLTRHDRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntroLtrHdrId.
     * @param value value to set the IntroLtrHdrId
     */
    public void setIntroLtrHdrId(BigDecimal value) {
        setAttributeInternal(INTROLTRHDRID, value);
    }

    /**
     * Gets the attribute value for ReleationTypeCode, using the alias name ReleationTypeCode.
     * @return the value of ReleationTypeCode
     */
    public String getReleationTypeCode() {
        return (String) getAttributeInternal(RELEATIONTYPECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReleationTypeCode.
     * @param value value to set the ReleationTypeCode
     */
    public void setReleationTypeCode(String value) {
        setAttributeInternal(RELEATIONTYPECODE, value);
    }

    /**
     * Gets the attribute value for PersonId, using the alias name PersonId.
     * @return the value of PersonId
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PersonId.
     * @param value value to set the PersonId
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for PassportNo, using the alias name PassportNo.
     * @return the value of PassportNo
     */
    public String getPassportNo() {
        return (String) getAttributeInternal(PASSPORTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PassportNo.
     * @param value value to set the PassportNo
     */
    public void setPassportNo(String value) {
        setAttributeInternal(PASSPORTNO, value);
    }

    /**
     * Gets the attribute value for DateOfBirth, using the alias name DateOfBirth.
     * @return the value of DateOfBirth
     */
    public Timestamp getDateOfBirth() {
        return (Timestamp) getAttributeInternal(DATEOFBIRTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for DateOfBirth.
     * @param value value to set the DateOfBirth
     */
    public void setDateOfBirth(Timestamp value) {
        setAttributeInternal(DATEOFBIRTH, value);
    }

    /**
     * Gets the attribute value for PlaceBirth, using the alias name PlaceBirth.
     * @return the value of PlaceBirth
     */
    public String getPlaceBirth() {
        return (String) getAttributeInternal(PLACEBIRTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlaceBirth.
     * @param value value to set the PlaceBirth
     */
    public void setPlaceBirth(String value) {
        setAttributeInternal(PLACEBIRTH, value);
    }

    /**
     * Gets the attribute value for PassportIssueDate, using the alias name PassportIssueDate.
     * @return the value of PassportIssueDate
     */
    public Timestamp getPassportIssueDate() {
        return (Timestamp) getAttributeInternal(PASSPORTISSUEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PassportIssueDate.
     * @param value value to set the PassportIssueDate
     */
    public void setPassportIssueDate(Timestamp value) {
        setAttributeInternal(PASSPORTISSUEDATE, value);
    }

    /**
     * Gets the attribute value for PassportEndDate, using the alias name PassportEndDate.
     * @return the value of PassportEndDate
     */
    public Timestamp getPassportEndDate() {
        return (Timestamp) getAttributeInternal(PASSPORTENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PassportEndDate.
     * @param value value to set the PassportEndDate
     */
    public void setPassportEndDate(Timestamp value) {
        setAttributeInternal(PASSPORTENDDATE, value);
    }

    /**
     * Gets the attribute value for ProTravelDate, using the alias name ProTravelDate.
     * @return the value of ProTravelDate
     */
    public Timestamp getProTravelDate() {
        return (Timestamp) getAttributeInternal(PROTRAVELDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProTravelDate.
     * @param value value to set the ProTravelDate
     */
    public void setProTravelDate(Timestamp value) {
        setAttributeInternal(PROTRAVELDATE, value);
    }

    /**
     * Gets the attribute value for ExpReturnDate, using the alias name ExpReturnDate.
     * @return the value of ExpReturnDate
     */
    public Timestamp getExpReturnDate() {
        return (Timestamp) getAttributeInternal(EXPRETURNDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpReturnDate.
     * @param value value to set the ExpReturnDate
     */
    public void setExpReturnDate(Timestamp value) {
        setAttributeInternal(EXPRETURNDATE, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the value of LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }


    /**
     * Gets the attribute value for Activeyn, using the alias name Activeyn.
     * @return the value of Activeyn
     */
    public String getActiveyn() {
        return (String) getAttributeInternal(ACTIVEYN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Activeyn.
     * @param value value to set the Activeyn
     */
    public void setActiveyn(String value) {
        setAttributeInternal(ACTIVEYN, value);
    }

    /**
     * @return the associated entity IntroLtrHdr_EOImpl.
     */
    public IntroLtrHdr_EOImpl getIntroLtrHdr_EO() {
        return (IntroLtrHdr_EOImpl) getAttributeInternal(INTROLTRHDR_EO);
    }

    /**
     * Sets <code>value</code> as the associated entity IntroLtrHdr_EOImpl.
     */
    public void setIntroLtrHdr_EO(IntroLtrHdr_EOImpl value) {
        setAttributeInternal(INTROLTRHDR_EO, value);
    }


    /**
     * @param introLtrLineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal introLtrLineId) {
        return new Key(new Object[] { introLtrLineId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }
}

